### ISSUE TITLE
Optional input files

### ISSUE THREAD

**Issue by felipeZ** [MD-Studio/cerise-client#9] opened 2017-11-24 10:15 UTC
In most typical workflows in [Gromacs](http://www.gromacs.org/) the [topology file](http://manual.gromacs.org/online/top.html) includes force field files using
the following notation
```
;
;	Example topology file
;
[ defaults ]
; nbfunc        comb-rule       gen-pairs       fudgeLJ fudgeQQ
  1             1               no              1.0     1.0

; The force field files to be included
#include "atomtypes.itp"
```
Usually the `include` file is already present in the source code of Gromacs but the user can also provide one or more files.
Therefore we need a mechanism that allows to pass optional files to the cerise-client job.

**Comment by LourensVeen** [comment] 2017-11-24 10:41
The issue is that there's a shell script in between, call_gromit.sh, which sets up the environment. CWL can do key-value pairs using something like `--key value`, but the shell script will have to parse that then. That's doable though, manually or using getopts or so. (Ideally, the CWL runner would be smart enough to create the environment, but that's a ways off still.)

CWL suppports optional inputs (using 'File?' for the type), but I've never tried them with Cerise and cwltiny. I think Cerise simply stages whatever the user provides, but cwltiny may do a string comparison on the type to figure out how to present the object to the call_gromit.sh executable, and that may fail with the extra question mark.

**Comment by felipeZ** [comment] 2017-11-24 12:13
We do not need those `include` files to be part of the input for gromit, we just need them to be in the same folder of the topology file.

**Comment by LourensVeen** [comment] 2017-11-24 12:28
Ah, but that means that they have to be staged together with the input, so somehow Cerise needs to know about them. There are actually two ways of doing this in CWL. We can specify them as secondaryFiles in the input, which means that they should be carried along with the primary file but don't need to be specified on the command line as they will be picked up automatically. The other option would be to use a Directory as an input, and pass the primary file name separately as a string. The internal includes would then do the rest.

The secondaryFiles thing is a bit messy, and I'm not sure if it's conceptually the best solution, I think it's intended for file formats that e.g. use separate files for metadata. What we have here is more akin to having a bunch of source code files with cross-references. Would be an interesting question to the CWL community actually.

At any rate, Cerise currently supports neither, as I've been putting off support for Directory type inputs until after the Xenon 2 port, and secondaryFiles is a bit messy in the object model. But the Xenon 2 port is in progress, so Directory support would be something for the near future.

**Comment by marcvdijk** [comment] 2017-11-24 13:23
Indeed, including atomtypes.itp may be important.

Atoms in a Gromacs topology link to certain types that are defined using an [atomtypes] section.
By default they are a part of the forcefield stored in the Gromacs distribution. 
If forcefield and parameter files for different molecules are added (small ligand or heme) that it
may be needed to update the atomtypes if the atoms do not fully map to the know [atomtypes]
or if deliberate changes are needed.

The only thing a user needs to do to include custom types is add the #include “atom types.itp”
in the top file and make sure that file is in the same directory as the topology file.

For LIE work it is likely we need this option although a [atomtypes] section should be part of the
ligand forcefield and parameter files for ACPYPE or ATB.

**Comment by LourensVeen** [comment] 2017-11-24 14:04
But do I understand correctly that what is in which file is essentially up to the user? Could they have multiple extra files with their own library of definitions, and want to send one or more of those along with the rest of the data? At which point does it become a better solution to use a single Directory input rather than an ever-growing bunch of optional files?

**Comment by marcvdijk** [comment] 2017-11-24 14:12
Indeed, in theory the user could include as many files using #include statements as he/she wants.
In practice it would be up to us by curating and combining these files into one file to bypass
those many include statements and make everything more concise and easy to handle. 
A microservice would be ideal to do that I would say. Perhaps Koen’s project could do that.

**Comment by LourensVeen** [comment] 2017-11-27 14:49
After some discussion, it does seem that secondaryFiles is the correct way of doing this. The Directory solution is ugly, because it's trying to shoehorn the solution into the wrong mechanism. So we should have secondaryFiles support. Cerise will have to stage them, and Cerise Client will have to be able to specify them. Probably the simplest thing is to add an optional extra parameter to `add_file` that takes an array of local file paths to submit along as secondaryFiles.

**Comment by LourensVeen** [comment] 2017-12-10 16:18
Support for secondaryFiles was added in Cerise, and here as well (5e1cbc7). I'd like to do an end-to-end practical test using the MDStudio specialisation before I close this though.

**Comment by LourensVeen** [comment] 2017-12-11 17:37
Seems to be working, the test failed, but due to the still incomplete energy step, Gromacs seems to have run just fine.

**Closed by LourensVeen** 2017-12-11 17:37 UTC
Labels: enhancement
